version: '2'
services:
  mysqldb:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zhang
      MYSQL_USER: www
      MYSQL_PASSWORD: www
      MYSQL_DATABASE: blog
    volumes:
        - ./config/:/etc/mysql/conf.d
  web:
    restart: always
    build: ./shuoz
    env_file: .env
    environment:
      DEBUG: 'true'
      PYTHONPATH: '/usr/src/app/shuoz'
      DJANGO_SETTINGS_MODULE: 'shuoz.settings'
    command: bash -c "gunicorn shuoz.wsgi:application -w 4 -k gevent -b :8000 --timeout 2000 --reload"
    volumes:
      - ./shuoz:/usr/src/app
    ports:
        - "8000"
    dns:
        - 114.114.114.114
        - 8.8.8.8
    links:
      - mysqldb
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./shuoz:/usr/src/app
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
    links:
      - web:web
volumes:
  mysqldata:
    driver: local
